# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs-apt"
      ref:  "7.6.0"
    concat:
      repo: "puppetlabs-concat"
      ref:  "6.2.0"
    dhcp:
      repo: "puppet-dhcp"
      ref:  "4.0.1"
    dns:
      repo: "theforeman-dns"
      ref:  "8.1.0"
    ini_setting:
      repo: "puppetlabs-inifile"
      ref:  "4.3.0"
    network:
      repo: "example42-network"
      ref:  "3.5.3"
    lvm:
      repo: "puppetlabs-lvm"
      ref:  "1.4.0"
    mount_core:
      repo: "puppetlabs-mount_core"
      ref:  "1.0.4"
    stdlib:
      repo: "puppetlabs-stdlib"
      ref:  "6.5.0"
    translate:
      repo: "puppetlabs-translate"
      ref:  "2.2.0"
